[versions]
agp = "8.4.0"
avvylib = "1.2.0"
evVersion = "1.0.4"
glide = "4.16.0"
gson = "2.10.1"
imagepicker = "2.1"
imagepickerVersion = "2.1"
jwtdecode = "2.0.2"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
loggingInterceptor = "4.12.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
popupDialog = "1.0.5"
retrofit = "2.11.0"
swiperefreshlayout = "1.1.0"
tedpermissionCoroutine = "3.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
avvylib = { module = "xyz.schwaab:avvylib", version.ref = "avvylib" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
easyvalidation-core = { module = "com.wajahatkarim:easyvalidation-core", version.ref = "evVersion" }
easyvalidation-toast = { module = "com.wajahatkarim:easyvalidation-toast", version.ref = "evVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepickerVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
jwtdecode = { module = "com.auth0.android:jwtdecode", version.ref = "jwtdecode" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
popup-dialog = { module = "com.saadahmedev.popup-dialog:popup-dialog", version.ref = "popupDialog" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
tedpermission-coroutine = { module = "io.github.ParkSangGwon:tedpermission-coroutine", version.ref = "tedpermissionCoroutine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

